name: Bazel

on: [push, pull_request]

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install numpy

            - name: "Build agents and observers"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk build //agents/... //observers/...

    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install numpy

            - name: "Report test coverage"
              run: |
                  tools/bazelisk coverage --combined_report=lcov --instrument_test_targets //agents/... //observers/...

            - name: "Submit report to Coveralls"
              uses: coverallsapp/github-action@1.1.3
              with:
                  github-token: ${{ secrets.github_token }}
                  path-to-lcov: bazel-out/_coverage/_coverage_report.dat

    lint:
        name: "Lint"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2

            - name: "Check code formatting"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk test --config lint //agents/... //observers/...

    test:
        name: "Test"
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version: ["3.8"]
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v2
              with:
                  python-version: "${{ matrix.python-version }}"

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install numpy

            - name: "Check unit tests"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk test //agents/... //observers/...
