name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2

            - name: "Build agents and observers"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk build //agents/... //observers/...

            - name: "Check code formatting"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk test --config lint //agents/... //observers/...

            - name: "Check unit tests"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk test //agents/... //observers/...

            - name: "Report test coverage"
              run: |
                  tools/bazelisk coverage --combined_report=lcov --instrument_test_targets //agents/... //observers/...

            - name: "Submit report to Coveralls"
              uses: coverallsapp/github-action@1.1.3
              with:
                  github-token: ${{ secrets.github_token }}
                  path-to-lcov: bazel-out/_coverage/_coverage_report.dat
