name: Release

on:
    release:
        types:
            - created

jobs:
    pi3hat_spine:
        name: "Add pi3hat spine to release assets"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                  tools/bazelisk build --config=pi64 //spines:pi3hat

            - uses: shogo82148/actions-upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ github.workspace }}/bazel-bin/spines/pi3hat
